[project]
name = "carte-des-kebabs-de-paris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.1"
dependencies = [
    "httpx>=0.28.1",
    "pandas>=2.3.3",
]
